### ISSUE TITLE
To be closed variables semantics changed

### ISSUE THREAD

**Issue by edubart** [dcurrie/nelua-bbtree#2]
Since commit https://github.com/edubart/nelua-lang/commit/470eb1c87c6b23fdc055e35298b9b837f4c27331 to-be-closed variables are now behaves like const variables, this matches the semantics of Lua 5.4, also avoid some misuses that were made in the tests of this library.

Since that commit the tests will fail with:

```lua
wbtforest-test.nelua:51:7: error: cannot assign a constant variable
      wbt2 = wbt1:insert(0, 42)
```

To fix is to remove any assignment with variables marked as `<close>`.

I've made that recent change specially after reading some misuses in the tests in this library.

**Comment by dcurrie** [comment]
Thanks @edubart !
